### ISSUE TITLE
Issue deploying management-API

### ISSUE THREAD

**Issue by pacospace** [thoth-station/management-api#255]
**Describe the bug**
Management-API cannot be redeployed. 

**To Reproduce**
Build and deploy new version of management-API

**Screenshots**
```

---> Serving application with gunicorn (thoth.management_api.openapi_server:app) ...
--
  | [2019-10-23 09:44:29 +0000] [1] [INFO] Starting gunicorn 19.9.0
  | [2019-10-23 09:44:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080  (1)
  | [2019-10-23 09:44:29 +0000] [1] [INFO] Using worker: sync
  | [2019-10-23 09:44:29 +0000] [33] [INFO] Booting worker with pid: 33
  | [2019-10-23 09:44:29 +0000] [34] [INFO] Booting worker with pid: 34
  | [2019-10-23 09:44:29 +0000] [35] [INFO] Booting worker with pid: 35
  | [2019-10-23 09:44:29 +0000] [37] [INFO] Booting worker with pid: 37
  | [2019-10-23 09:44:30 +0000] [33] [ERROR] Exception in worker process
  | Traceback (most recent call last):
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
  | worker.init_process()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
  | self.load_wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
  | self.wsgi = self.app.wsgi()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
  | self.callable = self.load()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
  | return self.load_wsgiapp()
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
  | return util.import_app(self.app_uri)
  | File "/opt/app-root/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
  | __import__(module)
  | File "/opt/app-root/src/thoth/management_api/openapi_server.py", line 26, in <module>
  | import connexion
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/__init__.py", line 5, in <module>
  | from .apis import AbstractAPI  # NOQA
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/__init__.py", line 1, in <module>
  | from .abstract import AbstractAPI  # NOQA
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/apis/abstract.py", line 10, in <module>
  | from ..operations import make_operation
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/operations/__init__.py", line 1, in <module>
  | from .abstract import AbstractOperation  # noqa
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/operations/abstract.py", line 10, in <module>
  | from ..decorators.response import ResponseValidator
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/response.py", line 12, in <module>
  | from .validation import ResponseBodyValidator
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/decorators/validation.py", line 15, in <module>
  | from ..json_schema import Draft4RequestValidator, Draft4ResponseValidator
  | File "/opt/app-root/lib/python3.6/site-packages/connexion/json_schema.py", line 7, in <module>
  | from openapi_spec_validator.handlers import UrlHandler
  | File "/opt/app-root/lib/python3.6/site-packages/openapi_spec_validator/__init__.py", line 7, in <module>
  | from openapi_spec_validator.factories import JSONSpecValidatorFactory
  | File "/opt/app-root/lib/python3.6/site-packages/openapi_spec_validator/factories.py", line 5, in <module>
  | from openapi_spec_validator.generators import (
  | File "/opt/app-root/lib/python3.6/site-packages/openapi_spec_validator/generators.py", line 12, in <module>
  | class SpecValidatorsGeneratorFactory:
  | File "/opt/app-root/lib/python3.6/site-packages/openapi_spec_validator/generators.py", line 19, in SpecValidatorsGeneratorFactory
  | 'properties': _validators.properties_draft4,
  | AttributeError: module 'jsonschema._validators' has no attribute 'properties_draft4'


```

**Comment by pacospace** [comment]
It seems to be a dependency issue between `openapi-spec-validator` and `jsonschema`

**Comment by pacospace** [comment]
I'll try pinning down `jsonschema<3.1.0`, so before the version issued this month.

**Comment by pacospace** [comment]
Indeed management-API is failing deployment since ~1 months when they issued new version of `jsonschema`.

**Comment by fridex** [comment]
> I could try pinning down `jsonschema<3.1.0`, so before the version issued this month. WDYT? @fridex

+1 if it will work

**Comment by pacospace** [comment]
It was not a dependency issue at the end :)
